// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPeFheeaxSRL0axAiwRDgYt_vcScNwqrg',
    appId: '1:960786630955:web:ad15faa4b9a871e5e8dd6e',
    messagingSenderId: '960786630955',
    projectId: 'taskmanager-6e4f2',
    authDomain: 'taskmanager-6e4f2.firebaseapp.com',
    storageBucket: 'taskmanager-6e4f2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt48A-DbIw4uVV3cW9LwTY-8s0h0xXU8U',
    appId: '1:960786630955:android:b5a6ace9e131ccb1e8dd6e',
    messagingSenderId: '960786630955',
    projectId: 'taskmanager-6e4f2',
    storageBucket: 'taskmanager-6e4f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkZiNS1m4aGSXk875wazUCqWFthqcZguU',
    appId: '1:960786630955:ios:3a14b095594b87cae8dd6e',
    messagingSenderId: '960786630955',
    projectId: 'taskmanager-6e4f2',
    storageBucket: 'taskmanager-6e4f2.firebasestorage.app',
    iosBundleId: 'com.example.taskmanagmentapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBogUiuIihlrE3nvBOXi9V-kAILEyESQqM',
    appId: '1:1098074934066:ios:07af5c2b8c71644a0d652b',
    messagingSenderId: '1098074934066',
    projectId: 'istakip-90248',
    storageBucket: 'istakip-90248.appspot.com',
    iosClientId: '1098074934066-dbk23odrimqjjo92k9jf1o5moj5qm5oe.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskmanagmentapp',
  );
}